host: 'Host'
port: '1234'
username: 'ABC'
password: 'XYZ'
database: 'Database'
table: 'tickets'

networkName: 'Example Network'

lang:
  title: 'XXXNETWORKNAMEXXX Ticket System'

players:
  doNotRemove:
    ticketstate: '5'
    type: ''
    description: ''
    usersteps: ''
