#host: 'Host'  -  Web address or IP address of your MySQL Server
#port: '3306'  -  MySQL port number
#username: 'ABC'  -  MySQL username
#password: 'XYZ'  -  MySQL password
#database: 'Database'  -  Database Name
#table: 'tickets'  -  Database table for your tickets
#serverName: 'Test'  -  The Bungee name of the Spigot server this plugin is installed on
#networkName: 'Example Network'  -  You minecraft network name, eg TreeboMC
#lang: title: 'XXXNETWORKNAMEXXX Ticket System'  - XXXNETWORKNAME will automatically be changed to the value in networkName. There is no need to change this.

apiLink: 'https://api.github.com/repos/TreeboMC/TreeboTickets/releases/latest'
releasePage: 'https://github.com/TreeboMC/TreeboTickets/releases/latest'
discordHook: ''
checkUpdates: 'true'
badge: '&3&l[&2Treebo Tickets&3&l]&r'
usePapi: false
bstatsIntegration: true
host: 'Host'
port: '3306'
username: 'ABC'
password: 'XYZ'
database: 'Database'
table: 'tickets'
tickettable: 'tickets'
ontimetable: 'newontime'
isLobbyServer: 'false'
lobbyServerName: 'hub'
maxClosedTickets: 50
socketIP: 127.0.0.1
socketPort: 9999

serverName: 'Test'
networkName: 'Example Network'

lang:
  title: 'Treebo Network Ticket System'

players:
  doNotRemove:
    ticketstate: '5'
    type: ''
    description: ''
    usersteps: ''

CustomHeads:
  Discord:
    ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: PLAYER_HEAD
    meta:
      ==: ItemMeta
      meta-type: SKULL
      display-name: Re-send to Discord
      internal: H4sIAAAAAAAAAE2PTU6DQBzF/xpNKnoHrwAWMF24aFpCIZ3BwvC5a2EaPmbahkJluurOG5h4D0/jwht4B2fp4iXv5ffe4ikACjwETc/Ya7vfVowqoEh3oG1X0eMdjDo6dH1LjwoAXI3gNlqznsIXFa6aJaVaJC7LhWPKTAKVeU59eHZ2kdjMHNPhki+m5lJM/nWNbh0bLB27ZbZb9Rseqcuxz+jC13IentJ4paMzrjCxNFynUuETJiX3yHRAsc+8ea5jOzSQjQbZNVJuadkcndG54J6N3nDdCERwlXKfZaTR5V4g4U62ifoCcA/XTiGP3Dy+f34HhXX5+JnFl/2vRH+pM7KQCgEAAA==
